# Generated by Django 2.2.6 on 2019-10-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191029_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='product_pic',
        ),
    ]
