# Generated by Django 2.2.6 on 2019-10-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191029_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_pic',
            new_name='product_image',
        ),
    ]
